#91 oracle jdk builds vs. open jdk builds understanding the differences
jobbole/translation-warehouse pull request #168
Opened 2019-06-04 08:25 UTC by youngLake

(提交翻译请使用下面的模板，其他类型pr请删除)

closes #91 

### 1.译者信息

***(请大家一定要填伯乐在线个人主页这一项，方便署名，🙏)***

|伯乐在线个人主页|新浪微博|
|:-------:|:------:|
|         |        |

### 2.疑问区

***(可在此区域列举有疑问的语句，提示校对人员重点关注)***

### 3.自查表

- [ ] 确认pr的目标分支是trans分支
- [ ] 确认pr不包含除译文以外的文件
- [ ] 补充评论区closes关键字以关联对应issue
- [ ] 通读文章，确保读者（非译者）能够理解文章内容（语言性，非技术性）
- [ ] 通读文章，确保语句通顺（有疑问语句请在疑问区提出）
- [ ] 符合排版规范要求

### 4.发布信息（译者无需填写）

发布链接：

-----

@hanxiaomax

2019-06-04 08:30 UTC, youngLake commented
提交译文 #91

2019-06-30 03:31 UTC, hanxiaomax requested changes
有些地方还需要理解了再翻译，不能直译原文，读者不好理解。另外排版实在是太乱了，原文排版乱是一个主要原因，翻译的时候可以优化一下。但是中英文译文之间好歹也要用空行隔开一下。

2019-06-30 03:31 UTC, hanxiaomax commented on translation/#91-Oracle-JDK-builds-vs.-OpenJDK-builds:-Understanding-the-differences.md
> +## We will explore this topic in-depth at [JAX London](https://jaxlondon.com/).
这一段都可以不要

2019-07-21 09:16 UTC, hanxiaomax approved these changes

2019-07-21 09:16 UTC, merged